name: Deploy

on:
  push:
    paths-ignore:
      - .github/**
      - .idea/**
      - .gitignore
      - CHANGELOG.md
      - README.md
  pull_request:
    paths-ignore:
      - .github/**
      - .idea/**
      - .gitignore
      - CHANGELOG.md
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: "**/.gradle/repositories/"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: "${{ runner.os }}-gradle-"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle deploy
        run: ./gradlew deploy
        shell: bash

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/${{ github.event.repository.name }}.jar
          compression-level: 0
